Update whisper.cpp version to 1.5.5
tazz4843/whisper-rs pull request #142
Opened 2024-04-23 16:09 UTC by arizhih

2024-05-15 22:30 UTC, tazz4843 reviewed
We should also regenerate bindings.rs. Given it was originally generated on a Linux machine, it should be regenerated on a Linux machine to minimize the diff. You can run `bindgen -o src/bindings.rs wrapper.h -- -Iwhisper.cpp/` in `/sys` to do so.

2024-05-15 22:30 UTC, tazz4843 commented on src/whisper_ctx.rs
> +    pub dtw_aheads_preset : whisper_rs_sys::whisper_alignment_heads_preset,
I can't tell the type of `whisper_alignment_heads_preset` from just this alone, but we should never expose raw integer data types to end-users of Rust libraries, as that would allow segfaults if set to a invalid value, something that should not be possible in safe Rust.

2024-05-15 22:30 UTC, tazz4843 commented on src/whisper_ctx.rs
> +    pub dtw_aheads: whisper_rs_sys::whisper_aheads,
Same as above, but we should create a wrapper struct.

2024-05-16 15:53 UTC, tazz4843 commented
See review comments

2024-05-17 12:57 UTC, arizhih commented
I think now it safe and it's not possible to use it incorrectly. All raw int values are checked inside whisper.cpp on state creation step and error is returned if values are incorrect.

2024-05-17 17:33 UTC, tazz4843 requested changes
One last nit but besides that looks good. Thanks :)

2024-05-17 17:33 UTC, tazz4843 commented on examples/audio_transcription.rs
> +    .map(|(n_text_layer, n_head)| whisper_rs_sys::whisper_ahead {
Should be using a public re-export at whisper-rs root instead of the -sys library

2024-05-17 22:12 UTC, arizhih commented on examples/audio_transcription.rs
> +    .map(|(n_text_layer, n_head)| whisper_rs_sys::whisper_ahead {
Thanks, I've missed it.

2024-05-27 10:23 UTC, arizhih commented
@tazz4843 Hi, whisper.cpp released new minor version, nothing changed in API. I've decided to update my PR to the latest release.

2024-05-27 13:43 UTC, thewh1teagle commented
@arizhih 
Tested on macOS. works great.

2024-05-28 22:01 UTC, tazz4843 approved these changes
Sorry this took so long, been dealing with the end of the school year :woozy_face: 
Looks good to me, thanks :)

2024-05-28 22:01 UTC, merged