To improve the usability of WhisperState with Rust's borrow checker
tazz4843/whisper-rs pull request #144
Opened 2024-04-26 08:16 UTC by XUJiahua

I encountered difficulties using the state correctly in callbacks due to challenges with the borrow checker. I adopted the approach suggested by @jcsoo in this discussion: https://github.com/tazz4843/whisper-rs/issues/86#issuecomment-2058049340.

Here's a summary of the refactoring changes:
1. Retain the original WhisperContext as the internal context, used privately within both the WhisperContext wrapper and WhisperState.
2. Designate the wrapper as WhisperContext and proxy all methods to the inner context, ensuring the public API remains unchanged.

I'd appreciate your feedback on this approach :)

2024-04-26 13:51 UTC, tazz4843 requested changes

2024-04-26 13:51 UTC, tazz4843 commented on src/whisper_state.rs
> +    pub fn pcm_to_mel(&self, pcm: &[f32], threads: usize) -> Result<(), WhisperError> {
Safe Rust has guarantees against race conditions and is why all of these functions were `&mut self`. We should leave mutation details to the end-user with a RwLock or Mutex depending on their use case, and keep `&mut self` unless digging through whisper.cpp code proves a function does not mutate internal state.

2024-04-28 00:34 UTC, XUJiahua commented on src/whisper_state.rs
> +    pub fn pcm_to_mel(&self, pcm: &[f32], threads: usize) -> Result<(), WhisperError> {
Yes, you are correct. After reviewing the whisper.cpp code, it does mutate internal state https://github.com/ggerganov/whisper.cpp/blob/master/whisper.cpp#L3045 . I will revert the changes accordingly.

2024-04-30 01:24 UTC, tazz4843 commented
Hmm looking at CI's failure it might be hard to work around without introducing some sort of internal lock (which should be avoided here I think) or removing the function entirely from WhisperState and moving it to WhisperContext.

2024-04-30 01:45 UTC, XUJiahua commented
> Hmm looking at CI's failure it might be hard to work around without introducing some sort of internal lock (which should be avoided here I think) or removing the function entirely from WhisperState and moving it to WhisperContext.

I just remove whisper_full_get_segment_speaker_turn_next from context and ci passed. I think it's ok to let user use full_get_segment_speaker_turn_next in state, the result is the same. https://github.com/ggerganov/whisper.cpp/blob/master/whisper.cpp#L6248

2024-04-30 03:24 UTC, tazz4843 commented
Looking at that link you sent uh it appears that function never worked: `ctx->state` is a nullptr with how whisper-rs initalizes whisper. Anyways this PR looks good thanks :)

2024-04-30 03:30 UTC, tazz4843 requested changes
Looked through CI and saw warnings, easy to fix here and may as well do so.

2024-04-30 03:30 UTC, tazz4843 commented on src/whisper_ctx.rs
GitHub doesn't let me add a comment to a line outside of this, but now that `WhisperInnerContext::create_state` was removed, line 2 `use crate::whisper_state::WhisperState;` is an unused import. 

ref https://github.com/tazz4843/whisper-rs/actions/runs/8887929077/job/24403983109?pr=144#step:5:54

2024-04-30 03:30 UTC, tazz4843 commented on src/whisper_ctx_wrapper.rs
> +    pub fn new(path: &str) -> Result<Self, WhisperError> {
Given this PR already involves breaking changes with the removal of the lifetime parameters we can probably just remove this function entirely given it's already deprecated, along with the same one on WhisperInnerContext.

2024-04-30 03:30 UTC, tazz4843 commented on src/whisper_ctx_wrapper.rs
> +    pub fn new_from_buffer(buffer: &[u8]) -> Result<Self, WhisperError> {
Same as above.

2024-04-30 05:51 UTC, XUJiahua commented
> Looked through CI and saw warnings, easy to fix here and may as well do so.

All deprecated functions were removed.

2024-04-30 05:58 UTC, tazz4843 approved these changes

2024-04-30 06:02 UTC, merged