feat: ROCm linux support
tazz4843/whisper-rs pull request #154
Opened 2024-05-31 08:19 UTC by newfla

The PR introduces the support for building the library with rocm/hipblas support.
The following changes have been made:
- Added  `hipblas` feature flag to` whisper-rs` and to `whisper-rs-sys`
- ROCm install folder can be optionally specified by `env::HIP_PATH`. Defaults to `/opt/rocm`
- Gpu targets can be optionally specified by `env::AMDGPU_TARGETS`
- Panics when targeting windows

Unfortunately I wasn't able to build whisper.cpp on windows: generated vcxproj refuse to use hipcc and defaults to cl.exe 😣

2024-05-31 22:02 UTC, tazz4843 requested changes

2024-06-01 09:51 UTC, newfla commented on Cargo.toml
> +hipblas = ["whisper-rs-sys/hipblas", "_gpu"]
The flag is strictly required:
When targeting hipblas, cmake defines both GGML_USE_HIPBLAS and GGML_USE_CUDA (see [CMakeLists.txt L402](https://github.com/ggerganov/whisper.cpp/blob/c7b6988678779901d02ceba1a8212d2c9908956e/CMakeLists.txt#L402)) 
In fact, the cuda and hip code are contained in the same src files, protected by precompiler directives (e.g. [mmq.cu L1076-L1120](https://github.com/ggerganov/whisper.cpp/blob/c7b6988678779901d02ceba1a8212d2c9908956e/ggml-cuda/mmq.cu#L1076-L1120))

2024-06-01 09:58 UTC, newfla commented on README.md
> +* `hipblas`: enable ROCm/hipBLAS support. Only available on linux. Implicitly enables hidden GPU flag at runtime.
See previous comment

2024-06-01 10:56 UTC, newfla commented on sys/build.rs
> +                panic!("Not supported yet!!!")
I've opened the issue https://github.com/ggerganov/whisper.cpp/issues/2202
Do you think it makes sense to include it in the error message?

2024-06-01 19:45 UTC, tazz4843 commented on Cargo.toml
> +hipblas = ["whisper-rs-sys/hipblas", "_gpu"]
Was unaware of that, sounds good.

2024-06-01 19:46 UTC, tazz4843 commented on sys/build.rs
> +                panic!("Not supported yet!!!")
It should at the least be noted that this is a ROCm issue and not act as if it's simply completely unsupported, adding a link to that upstream issue with a bit more detail in the panic message itself would be fine.

2024-06-02 10:44 UTC, newfla commented on sys/build.rs
> +                panic!("Not supported yet!!!")
I've modified the panic message

2024-06-02 16:04 UTC, tazz4843 approved these changes

2024-06-02 19:00 UTC, merged

2024-06-02 19:00 UTC, tazz4843 commented
Thanks :)