add full_get_token_bytes
tazz4843/whisper-rs pull request #171
Opened 2024-08-25 20:58 UTC by sribich

`full_get_segment_bytes exists`, but not `full_get_token_bytes`. 

For non English languages, whisper can split tokens on non-valid UTF8 boundaries making finer grained parsing impossible with the current `text` methods.

2024-09-01 23:17 UTC, tazz4843 requested changes
Needs `cargo fmt` as well

2024-09-01 23:17 UTC, tazz4843 commented on src/whisper_state.rs
> +        let c_str = unsafe { CStr::from_ptr(ret) };
Given that both of these functions have the same fundamental calling code, can we merge the common code between `_bytes` and `_text` and call the common (private) function from both?

2024-09-04 12:39 UTC, sribich commented on src/whisper_state.rs
> +        let c_str = unsafe { CStr::from_ptr(ret) };
I opted to copy how it was done for the existing `full_get_segment_text/bytes` functions. If the change is made here, it should probably also change for those functions to keep things consistent.

Thoughts?

2024-10-21 23:58 UTC, tazz4843 commented on src/whisper_state.rs
> +        let c_str = unsafe { CStr::from_ptr(ret) };
Oh wow I thought I responded to this forever ago, sorry about that. Yeah I think repeating this pattern on the others would be best.

2025-02-19 00:33 UTC, tazz4843 commented
Superseded by #202 (which adds this method indirectly)

2025-02-19 00:33 UTC, closed without merging