Fix build on Windows
tazz4843/whisper-rs pull request #18
Opened 2023-03-12 20:36 UTC by jbayardo

This PR moves the build to use `cmake` instead of `make`. The reason is that `whisper.cpp` doesn't support building for Windows using `make` at the moment. Moreover (even if it did), `cmake` solves several issues such as figuring out which specific compiler version to use and so on.

I have tested that this works on Windows, and it definitely does (at least for Windows 11). I can't really test it on any other OS, so I would appreciate some help for that.

Aside from the move to `cmake`, the only other thing I think might be a problem is the `std::fs::copy` call for move whisper to the `OUT_DIR`. The issue is that different OS will have a differently-named output file. `cargo` knows this and deals with it accordingly, but how to do so in the script I'm unsure.

2023-03-13 00:00 UTC, randomairborne commented
This change causes a build failure on Linux and MacOS:
```

  -- Build files have been written to: /Users/gxhut/Code/whisper-rs/sys/whisper.cpp/build
  [ 33%] Building C object CMakeFiles/whisper.dir/ggml.c.o
  [ 66%] Building CXX object CMakeFiles/whisper.dir/whisper.cpp.o
  [100%] Linking CXX static library libwhisper.a
  [100%] Built target whisper

  --- stderr
  thread 'main' panicked at 'Failed to copy libwhisper.a: Os { code: 2, kind: NotFound, message: "No such file or directory" }', sys/build.rs:94:6
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```

2023-03-13 03:32 UTC, jbayardo commented
Alright, I got WSL setup on my laptop and things are working on Ubuntu for me now. Please try again! :)

2023-03-13 17:12 UTC, tazz4843 requested changes

2023-03-14 03:00 UTC, jbayardo commented on sys/build.rs
> +    #[cfg(not(target_os = "windows"))]
I'll gladly do that if that's what you'd prefer, however, please consider:
1. The only reason this step can fail is if the library isn't there.
2. That would mean that all previous steps (i.e., compiling the static library) succeeded, but the path is incorrect for some reason.
3. The error very clearly points towards this line being the failure, so a person debugging such scenario would quickly realize that's what happened and fix the `build.rs`.

If it works by accident, then I'd call that a win!

2023-03-14 03:01 UTC, tazz4843 commented on sys/build.rs
> +    #[cfg(not(target_os = "windows"))]
Hmm fair enough

2023-03-14 03:01 UTC, tazz4843 approved these changes

2023-03-14 03:02 UTC, merged