refactor: delete map for State and expose struct with lifetime
tazz4843/whisper-rs pull request #39
Opened 2023-04-25 14:13 UTC by yuniruyuni

# What?

- Add lifetime parameter for WhisperState and now the instance cannot alive over than WhisperContext instance.
- Change WhisperContext interface by using WhisperState directly instead of Map from the key to State.
- Remove errors related for such keys

# Why?

refer: #37

2023-04-25 14:18 UTC, tazz4843 requested changes
Just one typo, but besides that, this looks good to me.

2023-04-25 14:18 UTC, tazz4843 commented on src/whisper_ctx.rs
> +    /// Ok(WhieperState) on success, Err(WhisperError) on failure.
```suggestion
    /// Ok(WhisperState) on success, Err(WhisperError) on failure.
```

2023-04-25 14:21 UTC, merged

2023-04-25 14:22 UTC, tazz4843 commented
Will do a publish later this afternoon my time.

2023-04-25 16:34 UTC, rroohhh commented
Is it intentional `WhisperState` is not `pub`? 
That way you cannot store it your own `struct`.

2023-04-25 16:38 UTC, rroohhh commented
Also returning a `*mut` pointer from a `&self` function seems pretty fishy.

2023-04-26 02:43 UTC, yuniruyuni commented
ah, wait..? I have rechecked it. In reality, `WhisperState` is already pub, isn't? -> https://github.com/tazz4843/whisper-rs/pull/39/files#diff-50d8a13384d2f9c3194627921beaf0996d62d47540cd0b3ff3fe6b80535dff99R5

and also `as_ptr()` is crate internal visibility (`pub(crate)`) so currently it's not ideal design but not so bad.

2023-04-26 02:57 UTC, yuniruyuni commented
oh, I get the meaning, `lib.rs` doesn't re-export WhisperState. OK now I have sent a PR about that. @@;
https://github.com/tazz4843/whisper-rs/pull/41