Fix windows cuda build
tazz4843/whisper-rs pull request #60
Opened 2023-05-25 02:26 UTC by jnnnnn

* add ggml-cuda.cu
* sort out linker paths using CUDA_PATH

2023-05-27 21:21 UTC, tazz4843 requested changes
Minor nitpick, otherwise looks fine.

2023-05-27 21:21 UTC, tazz4843 commented on sys/build.rs
> +        #[cfg(target_os = "windows")]
This should be changed to a cfg_if! block.

2023-05-29 14:20 UTC, tazz4843 approved these changes

2023-05-29 14:24 UTC, merged

2023-06-03 11:54 UTC, joseluis commented
Thaks! this PR also fixes compilation in linux when enabling the `cuda` feature with whisper-rs as a dependency.

I was going to open a new issue, when I saw this already solved it. A new patch release of whisper-sys would be nice.

2023-06-18 16:16 UTC, tazz4843 commented
0.6.1 of whisper-rs-sys has been published, sorry that took me so long @joseluis